import type { IconName } from '@/types/dashboard/client';
import type { VNode } from 'preact';
import type { IconType } from 'react-icons';
import {
  FiActivity,
  FiAlertTriangle,
  FiArrowDownCircle,
  FiArrowLeft,
  FiArrowRight,
  FiArrowUp,
  FiArrowUpCircle,
  FiArrowUpRight,
  FiBookOpen,
  FiCheck,
  FiCheckCircle,
  FiCheckSquare,
  FiChevronLeft,
  FiChevronRight,
  FiCode,
  FiCompass,
  FiCopy,
  FiCpu,
  FiDownloadCloud,
  FiEdit3,
  FiFile,
  FiFileText,
  FiGithub,
  FiGitPullRequest,
  FiGlobe,
  FiGrid,
  FiHeart,
  FiInfo,
  FiKey,
  FiLayers,
  FiLink2,
  FiMessageSquare,
  FiMoon,
  FiMoreHorizontal,
  FiPackage,
  FiPlay,
  FiPlus,
  FiRefreshCw,
  FiSearch,
  FiSettings,
  FiShield,
  FiSquare,
  FiStar,
  FiSun,
  FiTerminal,
  FiThumbsDown,
  FiThumbsUp,
  FiTrendingUp,
  FiUploadCloud,
  FiX,
  FiZap,
} from 'react-icons/fi';
import { LuBrain, LuGraduationCap, LuLightbulb } from 'react-icons/lu';
import { MdOutlineWifiTethering, MdPortableWifiOff } from 'react-icons/md';
import { RiMessageAi3Line, RiRobot2Fill } from 'react-icons/ri';

const registry = {
  grid: FiGrid,
  shield: FiShield,
  shieldCheck: FiShield,
  charter: FiFileText,
  search: FiSearch,
  sun: FiSun,
  moon: FiMoon,
  chevronRight: FiChevronRight,
  chevronLeft: FiChevronLeft,
  arrowUpRight: FiArrowUpRight,
  arrowRight: FiArrowRight,
  arrowUp: FiArrowUp,
  flame: FiZap,
  alertTriangle: FiAlertTriangle,
  layers: FiLayers,
  check: FiCheck,
  checkCircle: FiCheckCircle,
  plus: FiPlus,
  more: FiMoreHorizontal,
  file: FiFile,
  link: FiLink2,
  activity: FiActivity,
  upload: FiUploadCloud,
  key: FiKey,
  terminal: FiTerminal,
  globe: FiGlobe,
  code: FiCode,
  compass: FiCompass,
  live: FiTrendingUp,
  wifiOn: MdOutlineWifiTethering,
  wifiOff: MdPortableWifiOff,
  github: FiGithub,
  heart: FiHeart,
  book: FiBookOpen,
  star: FiStar,
  play: FiPlay,
  package: FiPackage,
  x: FiX,
  arrowLeft: FiArrowLeft,
  settings: FiSettings,
  pull: FiGitPullRequest,
  refresh: FiRefreshCw,
  download: FiDownloadCloud,
  brain: LuBrain,
  graduationCap: LuGraduationCap,
  copy: FiCopy,
  checkSquare: FiCheckSquare,
  square: FiSquare,
  upgrade: FiArrowUpCircle,
  pullDown: FiArrowDownCircle,
  chat: FiMessageSquare,
  messageAi: RiMessageAi3Line,
  robot: RiRobot2Fill,
  cpu: FiCpu,
  thumbsUp: FiThumbsUp,
  thumbsDown: FiThumbsDown,
  info: FiInfo,
  bulb: LuLightbulb,
  pencil: FiEdit3,
} satisfies Record<IconName, IconType>;

export const Icon = (props: { name: IconName }): VNode => {
  const Glyph = registry[props.name];
  return <Glyph aria-hidden='true' />;
};
