import type { AgentSpec } from '../types/core.js';

export const AGENT_SPECS: AgentSpec[] = [
  {
    key: 'claude',
    displayName: 'Claude Code',
    url: 'https://www.anthropic.com/claude-code',
    format: 'skill',
    layout: 'skill',
    dir: '.claude/skills',
  },
  {
    key: 'codex',
    displayName: 'Codex CLI',
    url: 'https://github.com/openai/codex',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'copilot',
    displayName: 'GitHub Copilot',
    url: 'https://code.visualstudio.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.github/skills',
  },
  {
    key: 'cursor-agent',
    displayName: 'Cursor',
    url: 'https://cursor.sh/',
    icon: 'cursor',
    format: 'skill',
    layout: 'skill',
    dir: '.cursor/skills',
  },
  {
    key: 'agy',
    displayName: 'Antigravity',
    url: 'https://antigravity.google/',
    icon: 'antigravity',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'opencode',
    displayName: 'opencode',
    url: 'https://opencode.ai/',
    format: 'markdown',
    dir: '.opencode/commands',
  },
  {
    key: 'windsurf',
    displayName: 'Windsurf',
    url: 'https://windsurf.com/',
    deprecated: { successor: 'devin-desktop' },
    format: 'markdown',
    dir: '.windsurf/workflows',
  },
  {
    key: 'devin',
    displayName: 'Devin for Terminal',
    url: 'https://cli.devin.ai/docs',
    format: 'skill',
    layout: 'skill',
    dir: '.devin/skills',
  },
  {
    key: 'devin-desktop',
    displayName: 'Devin Desktop',
    url: 'https://docs.devin.ai/desktop',
    icon: 'devin',
    format: 'skill',
    layout: 'skill',
    dir: '.devin/skills',
  },
  {
    key: 'kimi',
    displayName: 'Kimi Code',
    url: 'https://code.kimi.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.kimi/skills',
  },
  {
    key: 'lingma',
    displayName: 'Lingma',
    url: 'https://lingma.aliyun.com/',
    deprecated: { successor: 'qoder-cn' },
    format: 'skill',
    layout: 'skill',
    dir: '.lingma/skills',
  },
  {
    key: 'qoder-cn',
    displayName: 'Qoder CN',
    url: 'https://docs.qoder.cn/',
    icon: 'qodercli',
    format: 'skill',
    layout: 'skill',
    dir: '.lingma/skills',
  },
  {
    key: 'rovodev',
    displayName: 'RovoDev ACLI',
    url: 'https://www.atlassian.com/software/rovo-dev',
    format: 'skill',
    layout: 'skill',
    dir: '.rovodev/skills',
  },
  {
    key: 'trae',
    displayName: 'Trae',
    url: 'https://www.trae.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.trae/skills',
  },
  {
    key: 'vibe',
    displayName: 'Mistral Vibe',
    url: 'https://github.com/mistralai/mistral-vibe',
    format: 'skill',
    layout: 'skill',
    dir: '.vibe/skills',
  },
  {
    key: 'amazonq',
    displayName: 'Amazon Q Developer',
    url: 'https://aws.amazon.com/q/developer/',
    deprecated: { successor: 'kiro-cli' },
    format: 'markdown',
    dir: '.amazonq/prompts',
  },
  {
    key: 'amp',
    displayName: 'Amp',
    url: 'https://ampcode.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'continue',
    displayName: 'Continue',
    url: 'https://continue.dev/',
    format: 'continue-prompt',
    dir: '.continue/prompts',
  },
  {
    key: 'costrict',
    displayName: 'CoStrict',
    url: 'https://github.com/zgsm-ai/costrict',
    format: 'markdown',
    dir: '.roo/commands',
  },
  {
    key: 'crush',
    displayName: 'Crush',
    url: 'https://github.com/charmbracelet/crush',
    format: 'skill',
    layout: 'skill',
    dir: '.crush/skills',
  },
  {
    key: 'factory',
    displayName: 'Factory Droid',
    url: 'https://factory.ai/',
    icon: 'droid',
    format: 'skill',
    layout: 'skill',
    dir: '.factory/skills',
  },
  {
    key: 'auggie',
    displayName: 'Auggie CLI',
    url: 'https://docs.augmentcode.com/cli/overview',
    format: 'markdown',
    dir: '.augment/commands',
  },
  {
    key: 'bob',
    displayName: 'IBM Bob',
    url: 'https://www.ibm.com/products/bob',
    format: 'markdown',
    dir: '.bob/commands',
  },
  {
    key: 'cline',
    displayName: 'Cline',
    url: 'https://github.com/cline/cline',
    format: 'skill',
    layout: 'skill',
    dir: '.cline/skills',
  },
  {
    key: 'codebuddy',
    displayName: 'CodeBuddy CLI',
    url: 'https://www.codebuddy.ai/cli',
    format: 'markdown',
    dir: '.codebuddy/commands',
  },
  {
    key: 'iflow',
    displayName: 'iFlow CLI',
    url: 'https://docs.iflow.cn/en/cli/quickstart',
    format: 'markdown',
    dir: '.iflow/commands',
  },
  {
    key: 'junie',
    displayName: 'Junie',
    url: 'https://junie.jetbrains.com/',
    format: 'markdown',
    dir: '.junie/commands',
  },
  {
    key: 'kilocode',
    displayName: 'Kilo Code',
    url: 'https://github.com/Kilo-Org/kilocode',
    icon: 'kilo',
    format: 'skill',
    layout: 'skill',
    dir: '.kilo/skills',
  },
  {
    key: 'kiro-cli',
    displayName: 'Kiro CLI',
    url: 'https://kiro.dev/docs/cli/',
    format: 'markdown',
    dir: '.kiro/prompts',
  },
  {
    key: 'pi',
    displayName: 'Pi Coding Agent',
    url: 'https://pi.dev',
    format: 'markdown',
    dir: '.pi/prompts',
  },
  {
    key: 'qodercli',
    displayName: 'Qoder CLI',
    url: 'https://qoder.com/cli',
    format: 'markdown',
    dir: '.qoder/commands',
  },
  {
    key: 'qwen',
    displayName: 'Qwen Code',
    url: 'https://github.com/QwenLM/qwen-code',
    format: 'markdown',
    dir: '.qwen/commands',
  },
  {
    key: 'roo',
    displayName: 'Roo Code',
    url: 'https://roocode.com/',
    format: 'markdown',
    dir: '.roo/commands',
  },
  {
    key: 'shai',
    displayName: 'SHAI (OVHcloud)',
    url: 'https://github.com/ovh/shai',
    icon: 'ovhcloud',
    format: 'skill',
    layout: 'skill',
    dir: '.shai/skills',
  },
  {
    key: 'forge',
    displayName: 'Forge',
    url: 'https://forgecode.dev/',
    deprecated: { successor: 'forgecode' },
    format: 'forge',
    dir: '.forge/commands',
  },
  {
    key: 'forgecode',
    displayName: 'ForgeCode',
    url: 'https://forgecode.dev/',
    icon: 'forge',
    format: 'forge',
    dir: '.forge/commands',
  },
  {
    key: 'gemini',
    displayName: 'Gemini CLI',
    url: 'https://github.com/google-gemini/gemini-cli',
    format: 'gemini-toml',
    dir: '.gemini/commands',
    extension: '.toml',
  },
  {
    key: 'tabnine',
    displayName: 'Tabnine CLI',
    url: 'https://docs.tabnine.com/main/getting-started/tabnine-cli',
    deprecated: { endOfLife: '2026-12-31' },
    format: 'gemini-toml',
    dir: '.tabnine/agent/commands',
    extension: '.toml',
  },
  {
    key: 'goose',
    displayName: 'Goose',
    url: 'https://block.github.io/goose/',
    format: 'goose-yaml',
    dir: '.goose/recipes',
    extension: '.yaml',
  },
  {
    key: 'hermes',
    displayName: 'Hermes',
    url: 'https://hermes-agent.nousresearch.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.hermes/skills',
  },
  {
    key: 'adal',
    displayName: 'AdaL',
    url: 'https://docs.sylph.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.adal/skills',
  },
  {
    key: 'aiderdesk',
    displayName: 'AiderDesk',
    url: 'https://github.com/hotovo/aider-desk',
    format: 'skill',
    layout: 'skill',
    dir: '.aider-desk/skills',
  },
  {
    key: 'astrbot',
    displayName: 'AstrBot',
    url: 'https://astrbot.app/',
    format: 'skill',
    layout: 'skill',
    dir: 'data/skills',
  },
  {
    key: 'autohand',
    displayName: 'Autohand Code CLI',
    url: 'https://autohand.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.autohand/skills',
  },
  {
    key: 'codearts',
    displayName: 'CodeArts Agent (Huawei)',
    url: 'https://codearts.huaweicloud.com/',
    icon: 'huawei',
    format: 'skill',
    layout: 'skill',
    dir: '.codeartsdoer/skills',
  },
  {
    key: 'codemaker',
    displayName: 'Codemaker',
    url: 'https://github.com/codemakerai',
    format: 'skill',
    layout: 'skill',
    dir: '.codemaker/skills',
  },
  {
    key: 'codestudio',
    displayName: 'Code Studio',
    url: 'https://www.syncfusion.com/code-studio/',
    format: 'skill',
    layout: 'skill',
    dir: '.codestudio/skills',
  },
  {
    key: 'commandcode',
    displayName: 'Command Code',
    url: 'https://commandcode.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.commandcode/skills',
  },
  {
    key: 'cortex',
    displayName: 'Cortex Code (Snowflake)',
    url: 'https://docs.snowflake.com/en/user-guide/cortex-code/cortex-code',
    icon: 'snowflake',
    deprecated: { successor: 'coco' },
    format: 'skill',
    layout: 'skill',
    dir: '.cortex/skills',
  },
  {
    key: 'coco',
    displayName: 'Snowflake CoCo',
    url: 'https://www.snowflake.com/en/product/snowflake-coco/',
    icon: 'snowflake',
    format: 'skill',
    layout: 'skill',
    dir: '.cortex/skills',
  },
  {
    key: 'deepagents',
    displayName: 'Deep Agents (LangChain)',
    url: 'https://github.com/langchain-ai/deepagents',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'dexto',
    displayName: 'Dexto',
    url: 'https://dexto.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'eve',
    displayName: 'Eve',
    url: 'https://eve.dev/',
    format: 'skill',
    layout: 'skill',
    dir: 'agent/skills',
  },
  {
    key: 'inferencesh',
    displayName: 'inference.sh',
    url: 'https://inference.sh/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'jazz',
    displayName: 'Jazz',
    url: 'https://github.com/lvndry/jazz',
    format: 'skill',
    layout: 'skill',
    dir: 'skills',
  },
  {
    key: 'kode',
    displayName: 'Kode',
    url: 'https://github.com/shareAI-lab/kode',
    format: 'skill',
    layout: 'skill',
    dir: '.kode/skills',
  },
  {
    key: 'loaf',
    displayName: 'Loaf',
    url: 'https://github.com/levifig/loaf',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'mcpjam',
    displayName: 'MCPJam',
    url: 'https://mcpjam.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.mcpjam/skills',
  },
  {
    key: 'moxby',
    displayName: 'Moxby',
    url: 'https://moxby.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.moxby/skills',
  },
  {
    key: 'mux',
    displayName: 'Mux',
    url: 'https://mux.coder.com/',
    deprecated: { successor: 'xum' },
    format: 'skill',
    layout: 'skill',
    dir: '.mux/skills',
  },
  {
    key: 'xum',
    displayName: 'Xum',
    url: 'https://xum.coder.com/',
    icon: 'mux',
    format: 'skill',
    layout: 'skill',
    dir: '.xum/skills',
  },
  {
    key: 'ona',
    displayName: 'Ona',
    url: 'https://ona.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.ona/skills',
  },
  {
    key: 'openclaw',
    displayName: 'OpenClaw',
    url: 'https://docs.openclaw.ai/',
    format: 'skill',
    layout: 'skill',
    dir: 'skills',
  },
  {
    key: 'pochi',
    displayName: 'Pochi',
    url: 'https://getpochi.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.pochi/skills',
  },
  {
    key: 'promptscript',
    displayName: 'PromptScript',
    url: 'https://getpromptscript.dev/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'reasonix',
    displayName: 'Reasonix',
    url: 'https://github.com/esengine/DeepSeek-Reasonix',
    format: 'skill',
    layout: 'skill',
    dir: '.reasonix/skills',
  },
  {
    key: 'replit',
    displayName: 'Replit',
    url: 'https://replit.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'terramind',
    displayName: 'Terramind',
    url: 'https://terramind.com/',
    format: 'skill',
    layout: 'skill',
    dir: '.terramind/skills',
  },
  {
    key: 'tinycloud',
    displayName: 'Tinycloud',
    url: 'https://tinycloud.cloudglue.dev/',
    format: 'skill',
    layout: 'skill',
    dir: '.tinycloud/skills',
  },
  {
    key: 'warp',
    displayName: 'Warp',
    url: 'https://www.warp.dev/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'zed',
    displayName: 'Zed',
    url: 'https://zed.dev/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'zcode',
    displayName: 'ZCode',
    url: 'https://zcode.z.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.zcode/skills',
  },
  {
    key: 'zencoder',
    displayName: 'Zencoder',
    url: 'https://zencoder.ai/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'zenflow',
    displayName: 'Zenflow',
    url: 'https://zencoder.ai/zenflow',
    icon: 'zencoder',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'openhands',
    displayName: 'OpenHands',
    url: 'https://docs.openhands.dev/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
  {
    key: 'firebender',
    displayName: 'Firebender',
    url: 'https://docs.firebender.com/',
    format: 'markdown',
    dir: '.firebender/commands',
    extension: '.mdc',
  },
  {
    key: 'neovate',
    displayName: 'Neovate',
    url: 'https://neovateai.dev/',
    format: 'markdown',
    dir: '.neovate/commands',
  },
  {
    key: 'muse',
    displayName: 'Muse Code',
    url: 'https://dev.meta.ai/products/muse-code/',
    format: 'skill',
    layout: 'skill',
    dir: '.agents/skills',
  },
];
