import type { AgentSpec } from '../types/core.js';

export const AGENT_SPECS: AgentSpec[] = [
  {
    key: 'claude',
    displayName: 'Claude Code',
    format: 'skill',
    layout: 'skill',
    dir: '.claude/skills',
  },
  {
    key: 'codex',
    displayName: 'Codex CLI',
    format: 'skill',
    layout: 'skill',
    dir: '.codex/skills',
  },
  {
    key: 'copilot',
    displayName: 'GitHub Copilot',
    format: 'copilot-prompt',
    dir: '.github/prompts',
    extension: '.prompt.md',
  },
  {
    key: 'cursor-agent',
    displayName: 'Cursor',
    format: 'skill',
    layout: 'skill',
    dir: '.cursor/skills',
  },
  {
    key: 'agy',
    displayName: 'Antigravity',
    format: 'skill',
    layout: 'skill',
    dir: '.agent/skills',
  },
  {
    key: 'opencode',
    displayName: 'opencode',
    format: 'markdown',
    dir: '.opencode/commands',
  },
  {
    key: 'windsurf',
    displayName: 'Windsurf',
    format: 'markdown',
    dir: '.windsurf/workflows',
  },
  {
    key: 'devin',
    displayName: 'Devin for Terminal',
    format: 'skill',
    layout: 'skill',
    dir: '.devin/skills',
  },
  {
    key: 'kimi',
    displayName: 'Kimi Code',
    format: 'skill',
    layout: 'skill',
    dir: '.kimi/skills',
  },
  {
    key: 'lingma',
    displayName: 'Lingma',
    format: 'skill',
    layout: 'skill',
    dir: '.lingma/skills',
  },
  {
    key: 'rovodev',
    displayName: 'RovoDev ACLI',
    format: 'skill',
    layout: 'skill',
    dir: '.rovodev/skills',
  },
  {
    key: 'trae',
    displayName: 'Trae',
    format: 'skill',
    layout: 'skill',
    dir: '.trae/skills',
  },
  {
    key: 'vibe',
    displayName: 'Mistral Vibe',
    format: 'skill',
    layout: 'skill',
    dir: '.vibe/skills',
  },
  {
    key: 'amazonq',
    displayName: 'Amazon Q Developer',
    format: 'markdown',
    dir: '.amazonq/prompts',
  },
  {
    key: 'amp',
    displayName: 'Amp',
    format: 'markdown',
    dir: '.agents/commands',
  },
  {
    key: 'continue',
    displayName: 'Continue',
    format: 'markdown',
    dir: '.continue/prompts',
    extension: '.prompt',
  },
  {
    key: 'costrict',
    displayName: 'CoStrict',
    format: 'markdown',
    dir: '.cospec/commands',
  },
  {
    key: 'crush',
    displayName: 'Crush',
    format: 'markdown',
    dir: '.crush/commands',
  },
  {
    key: 'factory',
    displayName: 'Factory Droid',
    format: 'markdown',
    dir: '.factory/commands',
  },
  {
    key: 'auggie',
    displayName: 'Auggie CLI',
    format: 'markdown',
    dir: '.augment/commands',
  },
  {
    key: 'bob',
    displayName: 'IBM Bob',
    format: 'markdown',
    dir: '.bob/commands',
  },
  {
    key: 'cline',
    displayName: 'Cline',
    format: 'markdown',
    dir: '.clinerules/workflows',
  },
  {
    key: 'codebuddy',
    displayName: 'CodeBuddy CLI',
    format: 'markdown',
    dir: '.codebuddy/commands',
  },
  {
    key: 'iflow',
    displayName: 'iFlow CLI',
    format: 'markdown',
    dir: '.iflow/commands',
  },
  {
    key: 'junie',
    displayName: 'Junie',
    format: 'markdown',
    dir: '.junie/commands',
  },
  {
    key: 'kilocode',
    displayName: 'Kilo Code',
    format: 'markdown',
    dir: '.kilocode/workflows',
  },
  {
    key: 'kiro-cli',
    displayName: 'Kiro CLI',
    format: 'markdown',
    dir: '.kiro/prompts',
  },
  {
    key: 'pi',
    displayName: 'Pi Coding Agent',
    format: 'markdown',
    dir: '.pi/prompts',
  },
  {
    key: 'qodercli',
    displayName: 'Qoder CLI',
    format: 'markdown',
    dir: '.qoder/commands',
  },
  {
    key: 'qwen',
    displayName: 'Qwen Code',
    format: 'markdown',
    dir: '.qwen/commands',
  },
  {
    key: 'roo',
    displayName: 'Roo Code',
    format: 'markdown',
    dir: '.roo/commands',
  },
  {
    key: 'shai',
    displayName: 'SHAI (OVHcloud)',
    format: 'markdown',
    dir: '.shai/commands',
  },
  {
    key: 'forge',
    displayName: 'Forge',
    format: 'forge',
    dir: '.forge/commands',
  },
  {
    key: 'gemini',
    displayName: 'Gemini CLI',
    format: 'gemini-toml',
    dir: '.gemini/commands',
    extension: '.toml',
  },
  {
    key: 'tabnine',
    displayName: 'Tabnine CLI',
    format: 'gemini-toml',
    dir: '.tabnine/agent/commands',
    extension: '.toml',
  },
  {
    key: 'goose',
    displayName: 'Goose',
    format: 'goose-yaml',
    dir: '.goose/recipes',
    extension: '.yaml',
  },
  {
    key: 'hermes',
    displayName: 'Hermes',
    format: 'skill',
    layout: 'skill',
    dir: '.hermes/skills',
  },
  {
    key: 'adal',
    displayName: 'AdaL',
    format: 'skill',
    layout: 'skill',
    dir: '.adal/skills',
  },
  {
    key: 'aiderdesk',
    displayName: 'AiderDesk',
    format: 'skill',
    layout: 'skill',
    dir: '.aider-desk/skills',
  },
  {
    key: 'astrbot',
    displayName: 'AstrBot',
    format: 'skill',
    layout: 'skill',
    dir: 'data/skills',
  },
  {
    key: 'autohand',
    displayName: 'Autohand Code CLI',
    format: 'skill',
    layout: 'skill',
    dir: '.autohand/skills',
  },
  {
    key: 'codearts',
    displayName: 'CodeArts Agent (Huawei)',
    format: 'skill',
    layout: 'skill',
    dir: '.codeartsdoer/skills',
  },
  {
    key: 'codemaker',
    displayName: 'Codemaker',
    format: 'skill',
    layout: 'skill',
    dir: '.codemaker/skills',
  },
  {
    key: 'codestudio',
    displayName: 'Code Studio',
    format: 'skill',
    layout: 'skill',
    dir: '.codestudio/skills',
  },
];
