name: '🚀 CD — Publish'

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.event.repository.fork == false
    name: Release Please
    steps:
      - name: 🤝 Release Please
        uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/release/config.json
          manifest-file: .github/release/manifest.json

      - name: ➕ Actions - Checkout
        uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - name: ➕ Actions - Setup Node.js
        uses: actions/setup-node@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          check-latest: true
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: ➕ Cache dependencies
        uses: actions/cache@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          path: ~/.npm
          key: npm-linux-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-linux-

      - name: 📦 Installing Dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: 🚀 Building the Project
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build

      - name: 📥 Publishing Package
        if: ${{ steps.release.outputs.release_created }}
        run: npm publish --provenance

      - name: ➕ Cache dependencies (Website)
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key: npm-website-${{ hashFiles('website/package-lock.json') }}
          restore-keys: npm-website-

      - name: 📦 Installing Dependencies (Website)
        if: ${{ steps.release.outputs.release_created }}
        run: npm --prefix website ci

      - name: 🚀 Building Site
        if: ${{ steps.release.outputs.release_created }}
        run: npm --prefix website run build

      - name: 📤 Deploying Site
        if: ${{ steps.release.outputs.release_created }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          cname: lagune.ai
          publish_branch: 'website'
          allow_empty_commit: false
